//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Logn { get; set; }
        public string Pass { get; set; }
    }
}
